apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice1
  template:
    metadata:
      labels:
        app: myservice1
    spec:
      containers:
        - name: myservice1-container
          image: adriencalmesnil/myservice:1.0
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice2
  template:
    metadata:
      labels:
        app: myservice2
    spec:
      containers:
        - name: myservice2-container
          image: adriencalmesnil/myservice2:1.0
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: myservice1-service
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  type: ClusterIP
  selector:
    app: service1
---
apiVersion: v1
kind: Service
metadata:
  name: myservice2-service
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  type: ClusterIP
  selector:
    app: service2
---

